# Generated by Django 6.0.2 on 2026-03-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentbadge'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='challenges.skillchallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sessions', to='accounts.student')),
            ],
            options={
                'db_table': 'challenge_session',
                'unique_together': {('student', 'challenge', 'is_completed')},
            },
        ),
    ]
