# Generated by Django 6.0.2 on 2026-03-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengesession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengesession',
            unique_together=set(),
        ),
    ]
