# Generated by Django 6.0.2 on 2026-03-07 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_viewed', 'Application Viewed'), ('application_accepted', 'Application Accepted'), ('application_refused', 'Application Refused'), ('interview_proposed', 'Interview Proposed'), ('interview_confirmed', 'Interview Confirmed'), ('interview_cancelled', 'Interview Cancelled'), ('interview_reminder_24h', 'Interview Reminder 24h'), ('interview_reminder_1h', 'Interview Reminder 1h'), ('convention_generated', 'Convention Generated'), ('convention_student_signed', 'Convention Student Signed'), ('convention_company_signed', 'Convention Company Signed'), ('convention_validated', 'Convention Validated'), ('convention_rejected', 'Convention Rejected'), ('skill_verified', 'Skill Verified'), ('challenge_passed', 'Challenge Passed'), ('new_message', 'New Message'), ('company_validated', 'Company Validated'), ('offer_recommendation', 'Offer Recommendation')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='api_notific_user_id_4b7939_idx')],
            },
        ),
    ]
