import textwrap
from io import BytesIO
from django.core.files.base import ContentFile
from reportlab.lib.pagesizes import letter as letter_size
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def generate_reference_pdf(letter_obj, is_signed=False):
    """
    Generate a PDF for a ReferenceLetter object using ReportLab.
    Saves it to the ReferenceLetter's pdf_file field.
    """
    buffer = BytesIO()
    
    pdf = canvas.Canvas(buffer, pagesize=letter_size)
    width, height = letter_size
    student_name = f"{letter_obj.student.user.first_name} {letter_obj.student.user.last_name}".strip()
    
    pdf.setTitle(f"Reference Letter - {student_name}")

    # Header
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawCentredString(width / 2.0, height - 1 * inch, "Reference Letter")

    # Meta Info
    pdf.setFont("Helvetica", 12)
    pdf.drawString(1 * inch, height - 1.5 * inch, f"Date: {letter_obj.issue_date}")
    pdf.drawString(1 * inch, height - 1.8 * inch, f"Student: {student_name}")
    pdf.drawString(1 * inch, height - 2.1 * inch, f"Subject: {letter_obj.subject}")
    
    try:
        company_name = letter_obj.generated_by.companyprofile.company_name
    except AttributeError:
        company_name = f"{letter_obj.generated_by.first_name} {letter_obj.generated_by.last_name}"

    pdf.drawString(1 * inch, height - 2.4 * inch, f"Generated By: {company_name}")

    # Separator Line
    pdf.line(1 * inch, height - 2.6 * inch, width - 1 * inch, height - 2.6 * inch)

    # Content text logic
    pdf.setFont("Helvetica", 12)
    textobject = pdf.beginText(1 * inch, height - 3.2 * inch)
    textobject.setLeading(14)
    
    lines = []
    # simple wrapping logic
    for paragraph in (letter_obj.content or "").split('\n'):
        if not paragraph.strip():
            lines.append("")
        else:
            lines.extend(textwrap.wrap(paragraph, width=80))
    
    for line in lines:
        textobject.textLine(line)
        if textobject.getY() < 1 * inch: # simple pagination
            pdf.drawText(textobject)
            pdf.showPage()
            pdf.setFont("Helvetica", 12)
            textobject = pdf.beginText(1 * inch, height - 1 * inch)
            textobject.setLeading(14)
            
    pdf.drawText(textobject)

    # Footer / Signature
    if is_signed:
        signature_y = textobject.getY() - 1 * inch
        if signature_y < 1 * inch:
            pdf.showPage()
            signature_y = height - 1.5 * inch
        
        pdf.setFont("Helvetica-BoldOblique", 14)
        pdf.drawString(1 * inch, signature_y, "Digitally Signed")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(1 * inch, signature_y - 0.2 * inch, f"By: {company_name}")
        pdf.drawString(1 * inch, signature_y - 0.4 * inch, f"Verify authenticity using token:")
        pdf.drawString(1 * inch, signature_y - 0.55 * inch, str(letter_obj.verification_token))

    pdf.showPage()
    pdf.save()
    
    buffer.seek(0)
    file_name = f"Reference_{student_name.replace(' ', '_')}_{letter_obj.id}.pdf"
    
    # If a file already exists, it gets replaced/versioned by Django
    letter_obj.pdf_file.save(file_name, ContentFile(buffer.read()), save=True)
    buffer.close()
