# Generated by Django 6.0.2 on 2026-03-16 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_merge_20260314_0828'),
        ('offers', '0006_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('breakdown', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='offers.offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='accounts.student')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('student', 'offer')},
            },
        ),
    ]
