# Generated by Django 6.0.2 on 2026-03-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('speciality', models.CharField(max_length=100)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('challenge_type', models.CharField(choices=[('coding', 'Coding'), ('qcm', 'QCM (Multiple Choice)'), ('text', 'Written/Essay')], default='coding', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('test_cases', models.JSONField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=15)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'challenge_skillchallenge',
            },
        ),
        migrations.CreateModel(
            name='SkillChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('submitted_answers', models.JSONField(blank=True, null=True)),
                ('submitted_text', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.skillchallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_challenge_submissions', to='accounts.student')),
            ],
            options={
                'db_table': 'challenge_submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
