# Generated by Django 6.0.2 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challengesession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillchallenge',
            name='skill_name',
            field=models.CharField(max_length=100),
        ),
    ]
