# Generated by Django 6.0.2 on 2026-03-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('offers', '0004_skill_offer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='offers.skill'),
        ),
    ]
