# Generated by Django 6.0.2 on 2026-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_skills_student_wilaya_studentskill'),
        ('offers', '0005_offer_wilaya_challenge_challengesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', through='accounts.StudentSkill', to='offers.skill'),
        ),
    ]
