# Generated by Django 6.0.2 on 2026-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_webauthnauthentication_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
