# Generated by Django 6.0.2 on 2026-03-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_webauthnauthentication_webauthncredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
    ]
