# Generated by Django 6.0.2 on 2026-03-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.student')),
            ],
            options={
                'db_table': 'api_studentbadge',
                'unique_together': {('student', 'badge_name')},
            },
        ),
    ]
