# Generated by Django 6.0.2 on 2026-03-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_github_url_student_linkedin_url_and_more'),
        ('accounts', '0008_studentbadge'),
    ]

    operations = [
    ]
