# Generated by Django 6.0.2 on 2026-04-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260314_0828'),
        ('specialities', '0004_alter_competency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', through='accounts.StudentSkill', to='specialities.skill'),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialities.skill'),
        ),
    ]
