# Generated by Django 6.0.2 on 2026-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_skills_alter_studentskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
