# Generated by Django 6.0.2 on 2026-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_suspended_user_suspension_reason'),
        ('specialities', '0005_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='preferred_domains',
            field=models.ManyToManyField(blank=True, to='specialities.domain'),
        ),
        migrations.AddField(
            model_name='company',
            name='values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
