# Generated by Django 6.0.2 on 2026-05-02 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_suspended_user_suspension_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebauthnRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_webauthnregistration',
            },
        ),
    ]
