# Generated by Django 6.0.2 on 2026-05-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_webauthnregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthnregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_reg_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
