# Generated by Django 6.0.2 on 2026-05-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_mission_company_preferred_domains_and_more'),
        ('accounts', '0014_alter_webauthnregistration_user'),
    ]

    operations = [
    ]
