# Generated by Django 6.0.2 on 2026-04-26 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_company_rejection_reason_company_verified_at_and_more'),
        ('offers', '0009_add_company_notes_to_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='company_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company')),
            ],
            options={
                'db_table': 'api_companydocument',
            },
        ),
        migrations.CreateModel(
            name='CompanyTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='recruiter', max_length=50)),
                ('can_create_offers', models.BooleanField(default=True)),
                ('can_edit_offers', models.BooleanField(default=True)),
                ('can_delete_offers', models.BooleanField(default=False)),
                ('can_view_applications', models.BooleanField(default=True)),
                ('can_accept_applications', models.BooleanField(default=True)),
                ('can_refuse_applications', models.BooleanField(default=True)),
                ('can_sign_conventions', models.BooleanField(default=False)),
                ('can_invite_team_members', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_companyteammember',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_spot_1', models.DateTimeField(blank=True, null=True)),
                ('proposed_spot_2', models.DateTimeField(blank=True, null=True)),
                ('proposed_spot_3', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('interview_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In Person')], default='video', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending_student_selection', 'Pending Student Selection'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending_student_selection', max_length=30)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('student_confirmed', models.BooleanField(default=False)),
                ('student_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('reschedule_preferred_dates', models.JSONField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('undecided', 'Undecided')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='offers.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.company')),
            ],
            options={
                'db_table': 'api_interview',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('offset_minutes', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='company.interview')),
            ],
            options={
                'db_table': 'api_interviewreminder',
                'ordering': ['offset_minutes'],
            },
        ),
        migrations.CreateModel(
            name='StudentInterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('interviewer_professionalism', models.IntegerField()),
                ('clarity_of_questions', models.IntegerField()),
                ('company_culture_impression', models.IntegerField()),
                ('would_recommend_company', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='company.interview')),
            ],
            options={
                'db_table': 'api_studentinterviewfeedback',
            },
        ),
    ]
