# Generated by Django 6.0.2 on 2026-04-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreminder',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='company.interview'),
        ),
        migrations.AlterField(
            model_name='studentinterviewfeedback',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='company.interview'),
        ),
    ]
