# Generated by Django 6.0.2 on 2026-04-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_suspended_user_suspension_reason'),
        ('company', '0002_alter_interviewreminder_interview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='accounts.student')),
            ],
            options={
                'db_table': 'api_companyreview',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'student')},
            },
        ),
    ]
