# Generated by Django 6.0.2 on 2026-05-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_suspended_user_suspension_reason'),
        ('company', '0003_companyreview'),
        ('offers', '0016_merge_20260501_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_interviews', to='offers.application'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_interviews', to='accounts.company'),
        ),
    ]
