# Generated by Django 6.0.2 on 2026-04-27 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internshipvalidation',
            table=None,
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_status_change', 'User Status Change'), ('user_verify_id', 'User ID Verification'), ('company_verify', 'Company Verification'), ('internship_approve', 'Internship Approval'), ('internship_reject', 'Internship Rejection'), ('convention_validate', 'Convention Validation'), ('convention_reject', 'Convention Rejection'), ('portfolio_review', 'Portfolio Review'), ('taxonomy_change', 'Taxonomy Change'), ('bulk_action', 'Bulk Action')], max_length=50)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_adminactionlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
