# Generated by Django 6.0.2 on 2026-04-28 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_internshipvalidation_table_adminactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Before/After states or additional details'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_id',
            field=models.CharField(help_text='ID of the object acted upon', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_model',
            field=models.CharField(help_text='The model name (e.g., user, internshipvalidation)', max_length=100),
        ),
        migrations.AlterModelTable(
            name='internshipvalidation',
            table='api_internshipvalidation',
        ),
    ]
