# Generated by Django 6.0.2 on 2026-04-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_internshipvalidation_table_adminactionlog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internshipvalidation',
            table='api_internshipvalidation',
        ),
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
    ]
