# Generated by Django 6.0.2 on 2026-03-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_student_skills'),
        ('offers', '0005_offer_wilaya_challenge_challengesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signature'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='conventions/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='accounts.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='offers.offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='accounts.student')),
            ],
            options={
                'db_table': 'api_convention',
                'ordering': ['-created_at'],
            },
        ),
    ]
