# Generated by Django 6.0.2 on 2026-03-05 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='admin_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_conventions', to=settings.AUTH_USER_MODEL),
        ),
    ]
