# Generated by Django 6.0.2 on 2026-03-05 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0002_convention_admin_signed_convention_admin_signed_at_and_more'),
        ('offers', '0006_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='offers.application'),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='compensation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='convention',
            name='compensation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='convention',
            name='internship_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='convention',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_conventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convention',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='convention',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='convention',
            name='tasks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_student_signature', 'Pending Student'), ('pending_company_signature', 'Pending Company'), ('pending_admin_validation', 'Pending Admin'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
