# Generated by Django 6.0.2 on 2026-03-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0003_convention_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='company_signature_data',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='student_signature_data',
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_authentication_timestamp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_credential_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_fingerprint_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_authentication_timestamp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_credential_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_fingerprint_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_authentication_timestamp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_credential_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_fingerprint_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_user_agent',
            field=models.TextField(blank=True),
        ),
    ]
