# Generated by Django 6.0.2 on 2026-05-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0004_remove_convention_company_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='admin_signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
