# Generated by Django 6.0.2 on 2026-05-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0005_convention_admin_signature_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='admin_signature_data',
        ),
        migrations.AddField(
            model_name='convention',
            name='admin_signature_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='company_signature_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='student_signature_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='admin_authentication_timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='admin_credential_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='admin_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='admin_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_conventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='convention',
            name='admin_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
