# Generated by Django 6.0.2 on 2026-03-29 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_merge_20260314_0828'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Letter of Recommendation', max_length=255)),
                ('content', models.TextField(help_text='The actual body text of the letter before PDF generation', verbose_name='Letter Content')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='references/pdfs/')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_references', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_letters', to='accounts.student')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True, editable=False))
            ],
            options={
                'db_table': 'api_referenceletter',
            },
        ),
    ]
