# Generated by Django 6.0.2 on 2026-03-31 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceletter',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
