# Generated by Django 6.0.2 on 2026-03-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260314_0828'),
        ('specialities', '0002_competencyquiz_quizquestion_quizsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_submissions', to='specialities.competency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_submissions', to='accounts.student')),
            ],
            options={
                'db_table': 'specialities_portfoliosubmission',
            },
        ),
    ]
