# Generated by Django 6.0.2 on 2026-04-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_competencyquiz_quizquestion_quizsubmission'),
        ('specialities', '0002_portfoliosubmission'),
    ]

    operations = [
    ]
