# Generated by Django 6.0.2 on 2026-04-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260314_0828'),
        ('specialities', '0003_portfoliosubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizQuestion',
            new_name='SkillQuizQuestion',
        ),
        migrations.RenameModel(
            old_name='QuizSubmission',
            new_name='SkillQuizSubmission',
        ),
        migrations.AlterModelTable(
            name='skillquizquestion',
            table='specialities_skillquizquestion',
        ),
        migrations.AlterModelTable(
            name='skillquizsubmission',
            table='specialities_skillquizsubmission',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_required', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='specialities.speciality')),
            ],
            options={
                'db_table': 'specialities_skill',
                'unique_together': {('name', 'speciality')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='portfoliosubmission',
                    name='competency',
                ),
                migrations.AddField(
                    model_name='portfoliosubmission',
                    name='skill',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_submissions', to='specialities.skill'),
                ),
            ],
            database_operations=[]
        ),
        migrations.CreateModel(
            name='SkillQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=15)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='specialities.skill')),
            ],
            options={
                'db_table': 'specialities_skillquiz',
            },
        ),
        migrations.AlterField(
            model_name='skillquizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='specialities.skillquiz'),
        ),
        migrations.AlterField(
            model_name='skillquizsubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='specialities.skillquiz'),
        ),
    ]
