# Generated by Django 6.0.2 on 2026-04-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0004_alter_competency_unique_together_and_more'),
        ('offers', '0008_cleanup'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CompetencyQuiz',
                ),
                migrations.DeleteModel(
                    name='Competency',
                ),
            ],
            database_operations=[]
        ),
    ]
