# Generated by Django 6.0.2 on 2026-03-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_offer_type_offer_domain_offer_duration_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'api_domain',
            },
        ),
        migrations.CreateModel(
            name='DurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'api_durationoption',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'api_location',
            },
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'api_offertype',
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='internship_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
        migrations.AddField(
            model_name='offer',
            name='domains',
            field=models.ManyToManyField(related_name='offers', to='offers.domain'),
        ),
        migrations.AddField(
            model_name='offer',
            name='durations',
            field=models.ManyToManyField(related_name='offers', to='offers.durationoption'),
        ),
        migrations.AddField(
            model_name='offer',
            name='locations',
            field=models.ManyToManyField(related_name='offers', to='offers.location'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_types',
            field=models.ManyToManyField(related_name='offers', to='offers.offertype'),
        ),
    ]
