# Generated by Django 6.0.2 on 2026-03-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_domain_durationoption_location_offertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'api_skill',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='offers', to='offers.skill'),
        ),
    ]
