# Generated by Django 6.0.2 on 2026-03-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_skills'),
        ('offers', '0005_offer_wilaya_challenge_challengesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='offers.offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.student')),
            ],
            options={
                'db_table': 'api_application',
                'unique_together': {('student', 'offer')},
            },
        ),
    ]
