# Generated by Django 6.0.2 on 2026-04-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengesubmission',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeSubmission',
        ),
    ]
