# Generated by Django 6.0.2 on 2026-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_skills_alter_studentskill_skill'),
        ('offers', '0007_remove_challengesubmission_challenge_and_more'),
        ('specialities', '0004_alter_competency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='domains',
            field=models.ManyToManyField(related_name='offers', to='specialities.domain'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='offers', to='specialities.skill'),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
