# Generated by Django 6.0.2 on 2026-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
