# Generated by Django 6.0.2 on 2026-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_add_company_notes_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
