# Generated by Django 6.0.2 on 2026-04-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_skills_alter_studentskill_skill'),
        ('offers', '0009_add_company_notes_to_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=45)),
                ('method', models.CharField(choices=[('video', 'Video Call'), ('onsite', 'On-site'), ('phone', 'Phone Call')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='proposed', max_length=20)),
                ('join_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='offers.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.student')),
            ],
            options={
                'db_table': 'api_interview',
            },
        ),
    ]
