# Generated by Django 6.0.2 on 2026-04-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_offer_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Offer Created'), ('first_view', 'First View'), ('first_app', 'First Application'), ('milestone', 'Volume Milestone'), ('status_change', 'Status Change'), ('deadline_ext', 'Deadline Extended')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='offers.offer')),
            ],
            options={
                'db_table': 'api_offerevent',
                'ordering': ['-timestamp'],
            },
        ),
    ]
