# Generated by Django 6.0.2 on 2026-04-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_offer_deadline'),
        ('offers', '0011_message'),
    ]

    operations = [
    ]
