# Generated by Django 6.0.2 on 2026-04-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_suspended_user_suspension_reason'),
        ('offers', '0011_offerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OfferView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_views', to='offers.offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'db_table': 'api_offerview',
                'unique_together': {('offer', 'student', 'timestamp')},
            },
        ),
    ]
