# Generated by Django 6.0.2 on 2026-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_offer_views_count_offerview'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='boosted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
