# Generated by Django 6.0.2 on 2026-05-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_merge_0010_offer_deadline_0011_message'),
        ('offers', '0015_alter_application_status_alter_offer_status_and_more'),
    ]

    operations = [
    ]
