# Generated by Django 6.0.2 on 2026-05-04 18:14
#
# Originally this migration used raw SQL with "ADD COLUMN IF NOT EXISTS",
# which only works on MySQL 8.0.29+. Railway's MySQL plugin is on an older
# 8.x release that rejects that syntax with ER_PARSE_ERROR, blocking every
# deploy at this step.
#
# Rewritten to use a RunPython operation that checks INFORMATION_SCHEMA for
# the column first and only issues ADD COLUMN if it's missing. The semantics
# are identical (add the column if it isn't already there, then backfill
# student_id from the matching application row) but the SQL it executes is
# portable across MySQL 5.7, 8.0.x and MariaDB.
from django.db import migrations


def add_student_id_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'api_interview'
              AND COLUMN_NAME = 'student_id'
            """
        )
        column_exists = cursor.fetchone()[0]
        if not column_exists:
            cursor.execute("ALTER TABLE api_interview ADD COLUMN student_id BIGINT")
        cursor.execute(
            """
            UPDATE api_interview i
            JOIN api_application a ON i.application_id = a.id
            SET i.student_id = a.student_id
            WHERE i.student_id IS NULL
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_message_attachment_message_message_type_and_more'),
    ]

    operations = [
        migrations.RunPython(add_student_id_if_missing, reverse_code=migrations.RunPython.noop),
    ]
