# Generated by Django 6.0.2 on 2026-05-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_message_attachment_message_message_type_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_interview ADD COLUMN IF NOT EXISTS student_id BIGINT;
                UPDATE api_interview i 
                JOIN api_application a ON i.application_id = a.id 
                SET i.student_id = a.student_id
                WHERE i.student_id IS NULL;
            """,
            reverse_sql=""
        ),
    ]
