# Generated by Django 6.0.2 on 2026-05-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20260504_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('university_approved', 'University Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
