# Generated by Django 6.0.2 on 2026-03-01 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'offer')},
            },
        ),
    ]
