# Generated by Django 6.0.2 on 2026-03-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favoriteoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='favoriteoffer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteoffer',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='favoriteoffer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='FavoriteOffer',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
