SPECIALITY_SKILLS = {
    "Computer Science": [
        {"name": "Python",              "difficulty": "medium", "language": "python",     "type": "coding"},
        {"name": "Django",              "difficulty": "hard",   "language": "python",     "type": "coding"},
        {"name": "React.js",            "difficulty": "medium", "language": "javascript", "type": "coding"},
        {"name": "SQL",                 "difficulty": "easy",   "language": "sql",        "type": "coding"},
        {"name": "Data Structures",     "difficulty": "hard",   "language": "python",     "type": "coding"},
        {"name": "REST APIs",           "difficulty": "medium", "language": "python",     "type": "coding"},
        {"name": "Algorithms",          "difficulty": "hard",   "language": "python",     "type": "coding"},
        {"name": "Object Oriented Programming", "difficulty": "medium", "language": "python", "type": "coding"},
        {"name": "Git & Version Control",       "difficulty": "easy",   "language": None,     "type": "qcm"},
        {"name": "Linux & Terminal",            "difficulty": "easy",   "language": None,     "type": "qcm"},
        {"name": "Networking Fundamentals",     "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Database Design",             "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Cybersecurity Basics",        "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "System Design",               "difficulty": "hard",   "language": None,     "type": "text"},
        {"name": "Docker & DevOps",             "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "JavaScript",                  "difficulty": "medium", "language": "javascript", "type": "coding"},
        {"name": "TypeScript",                  "difficulty": "medium", "language": "javascript", "type": "coding"},
        {"name": "Machine Learning Basics",     "difficulty": "hard",   "language": "python",     "type": "coding"},
    ],

    "GP": [  # Génie des Procédés
        {"name": "Process Engineering Fundamentals", "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Thermodynamics",                   "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Mass & Energy Balance",            "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Chemical Reactions",               "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Process Safety",                   "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Fluid Mechanics",                  "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Heat Transfer",                    "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Distillation & Separation",        "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Reaction Kinetics",                "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Industrial Chemistry",             "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Process Control",                  "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Environmental Impact Assessment",  "difficulty": "easy",   "language": None, "type": "text"},
        {"name": "Material Balances",                "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Unit Operations",                  "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Corrosion & Materials",            "difficulty": "medium", "language": None, "type": "qcm"},
    ],

    "ST": [  # Sciences et Technologies
        {"name": "C Programming",          "difficulty": "medium", "language": "c",  "type": "coding"},
        {"name": "Electronics Basics",     "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Arduino",                "difficulty": "medium", "language": "c",  "type": "coding"},
        {"name": "Digital Logic Circuits", "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Electrical Principles",  "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Microcontrollers",       "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Signal & Systems",       "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Electromagnetism",       "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Sensors & Actuators",    "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Embedded Systems",       "difficulty": "hard",   "language": "c",  "type": "coding"},
        {"name": "PCB Design Concepts",    "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Telecommunications",     "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Renewable Energy",       "difficulty": "easy",   "language": None, "type": "text"},
        {"name": "Automation & PLC",       "difficulty": "hard",   "language": None, "type": "qcm"},
    ],

    "Polytechnique": [
        {"name": "Python",                    "difficulty": "medium", "language": "python", "type": "coding"},
        {"name": "Linear Algebra (NumPy)",    "difficulty": "hard",   "language": "python", "type": "coding"},
        {"name": "Signal Processing",         "difficulty": "hard",   "language": "python", "type": "coding"},
        {"name": "Engineering Mathematics",   "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Mechanics of Materials",    "difficulty": "hard",   "language": None,     "type": "text"},
        {"name": "Fluid Mechanics",           "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Thermodynamics",            "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Structural Analysis",       "difficulty": "hard",   "language": None,     "type": "text"},
        {"name": "Control Systems",           "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Numerical Methods",         "difficulty": "hard",   "language": "python", "type": "coding"},
        {"name": "Probability & Statistics",  "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Engineering Ethics",        "difficulty": "easy",   "language": None,     "type": "text"},
        {"name": "Project Management",        "difficulty": "easy",   "language": None,     "type": "qcm"},
        {"name": "CAD & Technical Drawing",   "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Material Science",          "difficulty": "medium", "language": None,     "type": "qcm"},
    ],

    "Medicine": [
        {"name": "Medical Terminology",        "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Clinical Case Analysis",     "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Pharmacology",               "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Human Anatomy",              "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Patient Diagnosis",          "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Medical Ethics",             "difficulty": "easy",   "language": None, "type": "text"},
        {"name": "Physiology",                 "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Pathology",                  "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Microbiology & Infections",  "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Surgery Fundamentals",       "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Emergency Medicine",         "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Radiology Basics",           "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Cardiology",                 "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Neurology Basics",           "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Pediatrics",                 "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Public Health",              "difficulty": "easy",   "language": None, "type": "text"},
        {"name": "Medical Research Methods",   "difficulty": "medium", "language": None, "type": "text"},
    ],

    "Pharmacy": [
        {"name": "Drug Interaction Analysis",   "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Pharmacokinetics",            "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Pharmaceutical Chemistry",    "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Drug Dosage Calculation",     "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Pharmacy Regulations",        "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Pharmacodynamics",            "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Drug Formulation",            "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Clinical Pharmacy",           "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Toxicology",                  "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Biotechnology in Pharmacy",   "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Herbal Medicine",             "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Drug Manufacturing (GMP)",    "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Antibiotic Stewardship",      "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Pharmaceutical Analysis",     "difficulty": "medium", "language": None, "type": "qcm"},
    ],

    "Biology": [
        {"name": "Cell Biology",                "difficulty": "easy",   "language": None,     "type": "qcm"},
        {"name": "Genetics & DNA",              "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Microbiology",                "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Bioinformatics with Python",  "difficulty": "hard",   "language": "python", "type": "coding"},
        {"name": "Ecology & Environment",       "difficulty": "easy",   "language": None,     "type": "text"},
        {"name": "Laboratory Techniques",       "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Biochemistry",                "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Molecular Biology",           "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Immunology",                  "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Evolutionary Biology",        "difficulty": "medium", "language": None,     "type": "qcm"},
        {"name": "Plant Biology",               "difficulty": "easy",   "language": None,     "type": "qcm"},
        {"name": "Marine Biology",              "difficulty": "medium", "language": None,     "type": "text"},
        {"name": "Neuroscience Basics",         "difficulty": "hard",   "language": None,     "type": "qcm"},
        {"name": "Biostatistics",               "difficulty": "medium", "language": "python", "type": "coding"},
        {"name": "Environmental Science",       "difficulty": "easy",   "language": None,     "type": "text"},
        {"name": "Virology",                    "difficulty": "hard",   "language": None,     "type": "qcm"},
    ],

    "English Literature": [
        {"name": "Essay Writing",           "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Text Analysis",           "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Literary Movements",      "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Grammar & Syntax",        "difficulty": "easy",   "language": None, "type": "qcm"},
        {"name": "Critical Thinking",       "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Research Writing",        "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Poetry Analysis",         "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Shakespeare & Classics",  "difficulty": "hard",   "language": None, "type": "qcm"},
        {"name": "Comparative Literature",  "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "Creative Writing",        "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Linguistics Basics",      "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Translation Studies",     "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Academic Writing",        "difficulty": "medium", "language": None, "type": "text"},
        {"name": "Discourse Analysis",      "difficulty": "hard",   "language": None, "type": "text"},
        {"name": "World Literature",        "difficulty": "medium", "language": None, "type": "qcm"},
        {"name": "Journalism & Media",      "difficulty": "easy",   "language": None, "type": "text"},
    ],
}